### ISSUE TITLE
QoL Change - Celestial Body Increment Button ++ & --

### ISSUE THREAD

**Issue by Poodmund** [ChrisAdderley/DynamicBatteryStorage#43]
I was thinking that it could be a potential QoL improvement if the Celestial Body selector button in the electrical panel could increment ++ with a left click and -- with a right click so that you don't have to cycle all the way through all the bodies if you accidentally pass the one you need.

![Untitled-1](https://user-images.githubusercontent.com/10106634/64735197-fbdef800-d4df-11e9-92d9-2e1867c15c38.png)

**Comment by yalov** [comment]
on the JNSQ I also have problem with "Body Orbital Height" slider, values too sparse:

[https://i.imgur.com/3IANPdl.gifv](https://i.imgur.com/3IANPdl.gifv)

**Comment by ChrisAdderley** [comment]
Both addressed in dev now, will be released... soon.

**Comment by ChrisAdderley** [comment]
Released.

**Comment by yalov** [comment]
Something is wrong with the Mean Solar Altitude slider (it's now 5km- 50Mm for Kerbin) and 
Body Orbital Height still can't be set to 100km, 300km, 500km. 
Proposing to limit min to Karman line and making slider logarithmic?
